version: "3.8"

services:
  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
