name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Copy project to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/project

    - name: Clean up existing containers
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        # Stop and remove any running containers
        docker ps -q --filter "ancestor=project_frontend" | xargs -r docker stop
        docker ps -q --filter "ancestor=project_backend" | xargs -r docker stop
        docker ps -q | xargs -r docker rm
        EOF

    - name: Check port usage
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        # Check if ports 3000 and 5000 are in use and terminate the processes if necessary
        if sudo lsof -i :3000; then
          echo "Port 3000 is in use. Killing the process..."
          sudo kill -9 $(sudo lsof -t -i :3000)
        else
          echo "Port 3000 is free"
        fi

        if sudo lsof -i :5000; then
          echo "Port 5000 is in use. Killing the process..."
          sudo kill -9 $(sudo lsof -t -i :5000)
        else
          echo "Port 5000 is free"
        fi
        EOF

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        cd /home/ec2-user/project
        docker-compose down --remove-orphans
        docker-compose up -d --build
        EOF
